import unittest
import asyncio
from app.util.idor_scan import check_idor  

class TestRunIdor(unittest.TestCase):
    def setUp(self):
        # Initialize the asyncio loop
        self.loop = asyncio.get_event_loop()

    def run_async_test(self, coro):
        # Utility method to run coroutine tests
        return self.loop.run_until_complete(coro)
    
    def test_invalid_url(self):
        # Test how the system handles an invalid URL format
        invalid_url = "http://192.168.124.132/lsdfsdfogin.php"
        result = self.run_async_test(check_idor(invalid_url))
        self.assertTrue(result['error'])
        self.assertIsNone(result['is_vulnerable'])
        self.assertIn('Invalid URL', result['error_message'])  

    def test_vulnerable_url(self):
        # Test with a known vulnerable URL
        vulnerable_url = "http://192.168.124.132/login/user.php?id=1"  
        result = self.run_async_test(check_idor(vulnerable_url,))
        self.assertTrue(result['is_vulnerable'])
        self.assertEquals(result['message'], "Potential IDOR Detected")

    def test_no_id_url(self):
        # Test with a known invulnerable URL
        invulnerable_url = "http://192.168.124.132/login_secured/login.php"  
        result = self.run_async_test(check_idor(invulnerable_url))
        self.assertFalse(result['is_vulnerable'])
        self.assertEquals(result['message'], "No ID detected in URL")

    
    def test_invulnerable_url(self):
        # Test with a known vulnerable URL
        vulnerable_url = "http://192.168.124.132/login_secured/user.php?id=1"  
        result = self.run_async_test(check_idor(vulnerable_url))
        self.assertFalse(result['is_vulnerable'])
        self.assertEquals(result['message'], "No IDOR Detected")

if __name__ == '__main__':
    unittest.main()
